#!/bin/bash
set +e -x -o pipefail
# fingerprint-DNANexus-applet 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    # cwd is $HOME=/home/dnanexus/

    ## Process inputs
    # On startup, home directory structure is defined by inputSpec in dxapp.json:
    # $HOME
    # ├── in
    # │   ├── input
    # │   │   └── RCMB56_P1.nodup.bam
    # │   ├── secondary_input
    # │   │   └── RCMB56_P1.nodup.bam.bai
    # │   └── snp_set
    # │       └── snp138Common.n1000.vh20140318.hg38.bed
    # │ ...
    # Environment variables are predefined for each input: $input, $input_path, $input_name $input_prefix
    # See https://documentation.dnanexus.com/developer/apps/bash#downloading-and-using-file-inputs

    dx-download-all-inputs
    mv $secondary_input_path $(dirname ${input_path})     # fingerprint expects .bam.bai file in same directory as .bam

    ## Parse and run command
    # Locations of executables eg. fingerprint are defined in dxapp.json.

    fp_home="/resources/fingerprint"
    cmd="python3 ${fp_home}/fingerprint.py --input ${input_path}"
    if [ -n "$snp_set" ]
    then
        cmd="${cmd} --snp_set ${snp_set_path}"
    fi
    if [ -n "$name" ]
    then
        cmd="${cmd} --name $name"
    fi
    if [ -n "$outfile" ]
    then
        cmd="${cmd} --output $outfile"
    fi

    eval $cmd

    ## Export outputs
    # Outputs must be configured as defined by outputSpec in dxapp.json:
    # $HOME
    # ├── out
    # │   └── fingerprint
    # │       └── RCMB56_P1.nodup.fp
    # │ ...

    mkdir -p $HOME/out/fingerprint
    mv *.fp out/fingerprint/ # fingerprint sends to cwd by default

    dx-upload-all-outputs
}
